Arewa Data Science Academy
Deep Learning Cohort1.0
Name: Bilqisu Ismail
Email: ismail.bilkisu@gmail.com
Title: Week 1 Solution

Exercises Solution

In [2]:
# Exercise 1- Solution

import torch
print(f"{torch.__version__}")

2.1.0+cu121


In [4]:
# Create random tensor
random_tensor_1 = torch.rand(size=(7, 7))
random_tensor_1

tensor([[0.2392, 0.1091, 0.6375, 0.7266, 0.8299, 0.7384, 0.0089],
        [0.0908, 0.3263, 0.5917, 0.6597, 0.8350, 0.4136, 0.2278],
        [0.4061, 0.8505, 0.8977, 0.5752, 0.9239, 0.5218, 0.3221],
        [0.6755, 0.6378, 0.5400, 0.1942, 0.4979, 0.0947, 0.5814],
        [0.4577, 0.1433, 0.4201, 0.2204, 0.8387, 0.3471, 0.2476],
        [0.7289, 0.8300, 0.6399, 0.4283, 0.5752, 0.1887, 0.8432],
        [0.8902, 0.4888, 0.8481, 0.9596, 0.2251, 0.5291, 0.9687]])

In [6]:
random_tensor_2= torch.rand(size=(1, 7))
random_tensor_2

tensor([[0.6643, 0.8444, 0.1936, 0.7785, 0.4869, 0.5638, 0.0811]])

In [8]:
# Perform matrix multiplication
matrix_multiplication = torch.matmul(random_tensor_1, random_tensor_2.T)
matrix_multiplication

tensor([[1.7612],
        [1.6222],
        [2.3797],
        [1.5861],
        [1.3021],
        [2.0972],
        [2.4018]])

In [9]:
# Set the random seed for reproducibility
torch.manual_seed(42)

# Initialize a linear layer with 2 input features and 6 output features
linear = torch.nn.Linear(in_features=2, out_features=6)

# Create a sample input tensor with shape (batch_size, 2)
# For the purpose of illustration, let's assume batch_size = 3
tensor_A = torch.rand((3, 2))

# Apply the linear layer to the input tensor
output = linear(tensor_A)

# Print the input, output, and shapes
print(f"Sample Input:\n{tensor_A}\n")
print(f"Sample Output:\n{output}\n")
print(f"Input shape: {tensor_A.shape}\n")
print(f"Output shape: {output.shape}")

Sample Input:
tensor([[0.2666, 0.6274],
        [0.2696, 0.4414],
        [0.2969, 0.8317]])

Sample Output:
tensor([[ 1.0348,  0.4592,  0.3892,  0.0690,  0.3858,  0.3514],
        [ 0.9272,  0.3378,  0.3622, -0.0094,  0.4842,  0.3286],
        [ 1.1711,  0.5868,  0.4136,  0.1433,  0.2987,  0.3971]],
       grad_fn=<AddmmBackward0>)

Input shape: torch.Size([3, 2])

Output shape: torch.Size([3, 6])


In [12]:
# Set manual seed
torch.manual_seed(0)

random_tensor_1 = torch.rand(size=(7, 7))
random_tensor_2= torch.rand(size=(1, 7))
# Matrix multiply tensors
seed_matrix_multiplication = torch.matmul(random_tensor_1, random_tensor_2.T)
seed_matrix_multiplication

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [3]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [6]:
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
gpu_tensor_1 = torch.rand(size=(2,3)).to(device)
gpu_tensor_2 = torch.rand(size=(2,3)).to(device)
gpu_tensor_1, gpu_tensor_2


Device: cuda


(tensor([[0.9734, 0.0859, 0.9417],
         [0.8727, 0.0228, 0.4643]], device='cuda:0'),
 tensor([[0.7506, 0.0052, 0.7921],
         [0.8364, 0.1988, 0.1660]], device='cuda:0'))

In [7]:
# Perform matmul on tensor_A and tensor_B

gpu_tensor_3 = torch.matmul(gpu_tensor_1, gpu_tensor_2.T)
gpu_tensor_3, gpu_tensor_3.shape

(tensor([[1.4769, 0.9875],
         [1.0229, 0.8116]], device='cuda:0'),
 torch.Size([2, 2]))

In [8]:
# Find maximum
max = torch.max(gpu_tensor_3)

# Find minimum
min = torch.min(gpu_tensor_3)
max, min

(tensor(1.4769, device='cuda:0'), tensor(0.8116, device='cuda:0'))

In [9]:
# Find arg max
max_index = torch.argmax(gpu_tensor_3)

# Find arg min
min_index = torch.argmin(gpu_tensor_3)
max_index, min_index

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor_4 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
random_tensor_5 = random_tensor_4.squeeze()

# Print out tensors
print(random_tensor_4)
print(random_tensor_5)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
