In [1]:
# Import PyTorch and matplotlib
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt
import zipfile
import pandas as pd
import numpy as np
import requests
from io import StringIO
# Check PyTorch version
torch.__version__

'2.1.0+cu121'

In [ ]:
#!wget https://archive.ics.uci.edu/dataset/607/synchronous+machine+data+set.zip -O data.zip

In [2]:
!unzip synchronous+machine+data+set.zip

Archive:  synchronous+machine+data+set.zip
 extracting: synchronous machine.csv  


In [3]:
dataset_name = "synchronous machine.csv"
data = pd.read_csv(dataset_name, delimiter=';', thousands=',')

In [4]:
numpy_data = data.values

In [5]:
original_data_tensors = torch.from_numpy(numpy_data)

In [6]:
original_data_tensors.size()

torch.Size([557, 5])

In [7]:
my_pi_tensor = torch.full(original_data_tensors.size(), 3.142)
my_pi_tensor

tensor([[3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        ...,
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420]])

In [8]:
# Check if GPU (CUDA) is available
device= "cuda"
if torch.cuda.is_available():
    # Move tensors to GPU
    original_data_tensors = original_data_tensors.to('cuda')
    my_pi_tensor = my_pi_tensor.to('cuda')
else: "cpu"
    # device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [9]:
# Print the first 13 rows of my_p_tensor
print("First 13 rows of my_p_tensor:")
print(my_pi_tensor[:13, :])

# Print the device location of my_p_tensor
print("\nTensor device location:")
print(my_pi_tensor.device)

# Print the data type of my_p_tensor
print("\nTensor data type:")
print(my_pi_tensor.dtype)

First 13 rows of my_p_tensor:
tensor([[3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420],
        [3.1420, 3.1420, 3.1420, 3.1420, 3.1420]], device='cuda:0')

Tensor device location:
cuda:0

Tensor data type:
torch.float32


In [10]:
# Calculate the 5th root of the sum of my_p_tensor
result = torch.pow(torch.sum(my_pi_tensor), 1/5)

print("5th root of the sum of my_p_tensor:", result.item())

5th root of the sum of my_p_tensor: 6.143364429473877


In [11]:
# Select the first and last 100 rows
my_data_tensor = torch.cat([original_data_tensors[:100], original_data_tensors[-100:]])

# Print the new tensor
print(my_data_tensor)
print("my_data_tensor shape:", my_data_tensor.shape)

tensor([[   3,   66,   34,  383, 1563],
        [   3,   68,   32,  372, 1552],
        [   3,    7,    3,   36,  154],
        [   3,   72,   28,  338, 1518],
        [   3,   74,   26,  317, 1497],
        [   3,   76,   24,  301, 1481],
        [   3,   78,   22,   29,  147],
        [   3,    8,    2,   28,  146],
        [   3,   82,   18,   25,  143],
        [   3,   84,   16,  221, 1401],
        [   3,   86,   14,  192, 1372],
        [   3,   88,   12,  165, 1345],
        [   3,    9,    1,  138, 1318],
        [   3,   92,    8,   98, 1278],
        [   3,   94,    6,   57, 1237],
        [   3,   96,    4,   37, 1217],
        [   3,   98,    2,   37, 1217],
        [   3,    1,    0,   37, 1217],
        [  31,   66,   34,  397, 1577],
        [  31,   68,   32,  414, 1594],
        [  31,    7,    3,  442, 1622],
        [  31,   72,   28,  369, 1549],
        [  31,   74,   26,  385, 1565],
        [  31,   76,   24,   31,  149],
        [  31,   78,   22,  325, 1505],


In [28]:
# you can do
# B = A[ row_start : row_end , column_start:column_end].clone()
# Extract the 4th column of  and convert it from int to float datatype
features = my_data_tensor[:, 3:4].clone().float().to(torch.float32)
features[:5]
#features.dtype

tensor([[383.],
        [372.],
        [ 36.],
        [338.],
        [317.]], device='cuda:0')

In [29]:
# Extract the last column of  and convert it from int to float dataty
target = my_data_tensor[:, -1].clone().detach().float().requires_grad_(True).to(torch.float32)

target[:5]

tensor([1563., 1552.,  154., 1518., 1497.], device='cuda:0',
       grad_fn=<SliceBackward0>)

In [38]:
# Normalize features
features_mean, features_std = features.mean(), features.std()
features_normalize  = (features -  features_mean)/ features_std
features_tensor = torch.tensor(features_normalize)
features_tensor= features_tensor.squeeze(dim=1)
features_tensor[:5]

<ipython-input-38-d4fd53deb38f>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  features_tensor = torch.tensor(features_normalize)


tensor([ 0.3188,  0.2666, -1.3291,  0.1051,  0.0054], device='cuda:0')

In [39]:
# Normalize target
target_mean, target_std = target.mean(), target.std()
target_normalize  = (target -  target_mean)/ target_std
target_tensor = torch.tensor(target_normalize, dtype=torch.float32 )
target_tensor[:5]

<ipython-input-39-c724df23ed1d>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  target_tensor = torch.tensor(target_normalize, dtype=torch.float32 )


tensor([ 0.3992,  0.3767, -2.4802,  0.3072,  0.2643], device='cuda:0')

In [40]:
train_split =int(0.75 *len(features))
X_train, y_train= features[:train_split], target[:train_split]
X_test, y_test = features[train_split:], target[train_split:]
len(X_train), len(y_train), len(X_test), len(y_test)

(150, 150, 50, 50)

In [41]:
class LinearModel(nn.Module):
  def __init__(self):
    super().__init__()

    self.linear_layer = nn.Linear(in_features=1,
                                      out_features=1)
  def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

torch.manual_seed(42)
model_1 = LinearModel()
model_1, model_1.state_dict()

(LinearModel(
   (linear_layer): Linear(in_features=1, out_features=1, bias=True)
 ),
 OrderedDict([('linear_layer.weight', tensor([[0.7645]])),
              ('linear_layer.bias', tensor([0.8300]))]))

In [42]:
# Create loss function
loss_fn = nn.L1Loss()

# Create optimizer
optimizer = torch.optim.SGD(params=model_1.parameters(),
                            lr=0.001)

In [43]:
torch.manual_seed(42)

# Set the number of epochs
epochs = 100

# Put data on the available device
X_train = X_train.to(device)
X_test = X_test.to(device)
y_train = y_train.to(device)
y_test = y_test.to(device)

for epoch in range(epochs):
    ### Training
    model_1.train().cuda() # train mode is on by default after construction

    # 1. Forward pass
    y_pred = model_1(X_train)

    # 2. Calculate loss
    loss = loss_fn(y_pred, y_train)

    # 3. Zero grad optimizer
    optimizer.zero_grad()

    # 4. Loss backward
    loss.backward()

    # 5. Step the optimizer i.e update parameters
    optimizer.step()

    ### Testing
    model_1.eval() # put the model in evaluation mode for testing (inference)
    # 1. Forward pass
    with torch.inference_mode():
        test_pred = model_1(X_test)

        # 2. Calculate the loss
        test_loss = loss_fn(test_pred, y_test)

    if epoch % 20 == 0:
        print(f"Epoch: {epoch} | Train loss: {loss} | Test loss: {test_loss}")

Epoch: 0 | Train loss: 1137.8447265625 | Test loss: 1132.9984130859375
Epoch: 20 | Train loss: 760.996826171875 | Test loss: 724.0993041992188
Epoch: 40 | Train loss: 753.1162719726562 | Test loss: 771.3173828125
Epoch: 60 | Train loss: 753.0445556640625 | Test loss: 776.51806640625
Epoch: 80 | Train loss: 753.0410766601562 | Test loss: 776.85595703125


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([150])) that is different to the input size (torch.Size([150, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([50])) that is different to the input size (torch.Size([50, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
